import {readFile, writeFile, mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {sections, version, checkGroups} from '../handbook/content.mjs';

const root = new URL('../', import.meta.url);
const read = path => readFile(new URL(path, root), 'utf8');
const css = await read('handbook/guide.css');
const js = await read('handbook/guide.js');
const favicon = 'data:image/svg+xml;base64,' + Buffer.from(await read('public/favicon.svg')).toString('base64');
const photo = async name => 'data:image/jpeg;base64,' + (await readFile(new URL(`handbook/assets/${name}.jpg`, root))).toString('base64');
const photos = {PHOTO_BUDGIE: await photo('budgerigar'), PHOTO_CONURE: await photo('green-cheeked-conure')};
const escape = s => s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const nav = sections.map((s,i)=>`<a href="#${s.id}"><span>${String(i+1).padStart(2,'0')}</span>${s.title.split('：')[0]}</a>`).join('');
const content = sections.map((s,i)=>`<section class="chapter ${s.id === 'emergency' ? 'chapter-emergency' : ''}" id="${s.id}" aria-labelledby="title-${s.id}"><header class="chapter-heading"><span class="chapter-number" aria-hidden="true">${String(i+1).padStart(2,'0')}</span><div><h2 id="title-${s.id}">${s.title}</h2><p class="chapter-intro">${s.intro}</p></div></header><div class="essentials"><span class="label">先记住这${s.essentials.length === 1 ? '一点' : '几件事'}</span><ul>${s.essentials.map(x=>`<li>${x}</li>`).join('')}</ul></div>${s.body.replace('头部波纹、弯喙与长尾等外形特征','黄色头部、蓝色鼻膜、黑色斑纹与弯喙的面部特写')}</section>`).join('\n');
const checks = checkGroups.map(g=>`<section class="check-group" data-group="${g.id}" aria-labelledby="check-${g.id}"><header><h3 id="check-${g.id}">${g.title}</h3><span class="check-date" data-date="${g.id}"></span></header><p class="check-meter" data-meter="${g.id}" aria-live="polite">0 / ${g.items.length} 项完成</p>${g.items.map(([id,text])=>`<label class="check-item"><input type="checkbox" data-check="${g.id}-${id}" data-group="${g.id}"><span>${text}</span></label>`).join('')}<button class="reset-group" type="button" data-reset="${g.id}">重置${g.id==='daily'?'今日':g.id==='weekly'?'本周':'准备'}勾选</button></section>`).join('');

let html = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="description" content="面向零基础新手的虎皮与小太阳鹦鹉照护手册：接鸟准备、饮食、放飞安全、行为、健康与急症，支持手机和完整离线阅读。"><meta name="theme-color" content="#f4efe4"><title>鹦鹉饲养指南｜虎皮与小太阳·新手图解版</title><style>${css}</style></head>
<body><a href="#main" class="skip-link">跳到正文</a><header class="topbar"><a class="brand" href="#top"><span class="brand-icon" aria-hidden="true">羽</span><span>鹦鹉照护手册<span id="currentChapter" class="current-label">虎皮 · 小太阳</span></span></a><div class="toolbar"><button type="button" class="top-search" data-open="search" aria-label="搜索手册" aria-haspopup="dialog"><span aria-hidden="true">⌕</span><span class="search-label">搜索注意事项</span><span class="keyhint" aria-hidden="true">/</span></button><button type="button" id="themeToggle" aria-pressed="false" aria-label="切换到深色模式">◐</button><button class="desktop-only" type="button" data-open="toc" aria-haspopup="dialog">目录</button></div><div class="progress" id="progressBar" aria-hidden="true"></div></header>
<div class="layout" id="top"><aside class="sidebar" aria-label="桌面章节目录"><p class="eyebrow">一本随手查的照护手册</p><nav class="toc-list">${nav}</nav><a class="side-emergency" href="#emergency">急症：先看这里 ↗</a></aside><main class="main" id="main"><noscript><p class="no-js">当前查看器未运行脚本。正文和图片仍可离线阅读；可展开各节内容。搜索、清单保存和主题切换需在支持脚本的浏览器中使用。</p></noscript><div class="resume" id="resumeCard" hidden><a id="resumeLink" href="#start">继续上次阅读</a><button type="button" id="dismissResume">暂不继续</button></div><section class="intro"><p class="eyebrow">零基础也能一步步学 · 图解照护指南</p><h1>从第一天开始，<br><em>学会照顾你的鹦鹉。</em></h1><p>重点认识虎皮与小太阳。先做对安全、吃喝和观察，再慢慢学会相处；不懂的词、拿不准的操作，都可以随时回来查。</p><div class="quick-links"><a href="#start">准备接鸟<span>用品与交接事项</span></a><a href="#species">认识我的鸟<span>虎皮 / 小太阳专属</span></a><a href="#checklists">今天怎么照顾<span>每日与每周清单</span></a><a class="urgent" href="#emergency">身体出现异常<span>急症信号与转运</span></a></div><p class="read-note">先读每节的要点，再展开具体步骤。<a href="#newbird">鸟刚到家？</a>　<a href="#checklists">需要离线版？</a></p></section>
${content}
<footer><div class="footer-row"><strong>鹦鹉照护手册 · 新手图解版</strong><span>内容版本 ${version} · ${sections.length} 个主题</span><a href="#top">回到开头 ↑</a></div><p>用于日常照护教育与就诊准备，不能替代鸟类兽医检查。医疗、特殊饮食、隔离与育雏方案应按具体物种与个体决定。</p><p class="credits">真实照片：虎皮 © Аимаина хикари；绿颊锥尾 © Hugo Hulsberg（hhulsberg）。均以 CC0 1.0 提供；仅缩小图像尺寸。<a href="https://commons.wikimedia.org/wiki/File:Melopsittacus_undulatus_Kiev2.JPG" rel="noopener noreferrer" target="_blank">虎皮照片信息</a> · <a href="https://commons.wikimedia.org/wiki/File:Green-cheeked_Parakeet_(Pyrrhura_molinae_australis),_Santa_B%C3%A1rbara,_Jujuy,_Argentina_1.jpg" rel="noopener noreferrer" target="_blank">绿颊照片信息</a>。图解为独立编排的教学示意，不是疾病诊断图。</p><p>离线阅读不需要联网；照片信息链接需要联网。任务记录仅留在当前设备。</p></footer></main></div>
<nav class="bottom-nav" aria-label="手机快捷导航"><button type="button" data-open="toc" aria-haspopup="dialog"><span class="nav-icon" aria-hidden="true">☰</span>目录</button><button type="button" data-open="search" aria-haspopup="dialog"><span class="nav-icon" aria-hidden="true">⌕</span>搜索</button><a href="#checklists"><span class="nav-icon" aria-hidden="true">✓</span>清单</a><a class="urgent" href="#emergency"><span class="nav-icon" aria-hidden="true">!</span>急症</a></nav>
<div id="tocModal" class="modal" hidden><section class="modal-sheet" role="dialog" aria-modal="true" aria-labelledby="tocTitle" tabindex="-1"><header class="modal-header"><h2 id="tocTitle">章节目录</h2><button type="button" data-close aria-label="关闭目录">✕</button></header><div class="modal-body"><nav class="toc-list" aria-label="全部章节">${nav}</nav></div></section></div>
<div id="searchModal" class="modal" hidden><section class="modal-sheet" role="dialog" aria-modal="true" aria-labelledby="searchTitle" tabindex="-1"><header class="modal-header"><h2 id="searchTitle">搜索手册</h2><button type="button" data-close aria-label="关闭搜索">✕</button></header><div class="modal-body"><label class="search-field"><span class="sr-only" hidden>输入关键词</span><input id="searchInput" type="search" aria-label="搜索关键词" placeholder="如：小太阳、换粮、咬人、牛油果" enterkeyhint="search" autocomplete="off"><button id="searchClear" type="button">清除</button></label><div class="suggestions">${['虎皮','小太阳','不吃','换粮','咬人','微信'].map(s=>`<button type="button" data-query="${escape(s)}">${s}</button>`).join('')}</div><p id="searchStatus" class="search-status" role="status" aria-live="polite">输入关键词，定位具体步骤；不会隐藏其他章节。</p><ul class="results" id="searchResults"></ul></div></section></div><div class="toast" id="toast" role="status" hidden></div>
<script>${js}</script></body></html>`;
html = html.replace('<div id="checkGroups"></div>',`<div id="checkGroups">${checks}</div>`).replace(/\{\{(PHOTO_[A-Z]+)\}\}/g,(_,name)=>photos[name]);
html = html.replace('<title>', `<link rel="icon" href="${favicon}"><title>`);
if (/\{\{PHOTO_/.test(html)) throw new Error('Unresolved image');
for (const target of ['docs/index.html','public/鹦鹉饲养指南.html','鹦鹉饲养指南.html']) {
  await mkdir(new URL(target.includes('/') ? target.slice(0,target.lastIndexOf('/')) + '/' : './',root), {recursive:true});
  await writeFile(new URL(target,root),html);
}
console.log(`Built ${sections.length} chapters; ${Buffer.byteLength(html)} bytes; SHA256 ${createHash('sha256').update(html).digest('hex')}`);
